# Post hoc exploratory analyses

```{r}
df.S1 <- subset(Data_Meta_Raw.wide, Study == 1)
df.S2 <- subset(Data_Meta_Raw.wide, Study == 2)
df.S3 <- subset(Data_Meta_Raw.wide, Study == 3)
df.S4 <- subset(Data_Meta_Raw.wide, Study == 4)
df.S5 <- subset(Data_Meta_Raw.wide, Study == 5)
df.S6 <- subset(Data_Meta_Raw.wide, Study == 6)

df.cor.S1 <- df.S1[ , c('SleepQualCro', 'SleepQualAcu', 'SleepQuantCro', 'SleepQuantAcu',
               'CRT_TOT', 'Num_TOT', 'AOT_TOT',
               'Psych_TOT', 'Mach_TOT', 'Narc_TOT',
               'Moral_DIL')]

df.cor.S2 <- df.S2[ , c('SleepQualCro', 'SleepQualAcu', 'SleepQuantCro', 'SleepQuantAcu',
               'CRT_TOT', 'Num_TOT', 'AOT_TOT',
               'Psych_TOT', 'Mach_TOT', 'Narc_TOT',
               'Moral_SCA')]

df.cor.S3 <- df.S3[ , c('SleepQualCro', 'SleepQualAcu', 'SleepQuantCro', 'SleepQuantAcu',
               'CRT_TOT', 'Num_TOT', 'AOT_TOT',
               'Psych_TOT', 'Mach_TOT', 'Narc_TOT',
               'Moral_SCA')]

df.cor.S4 <- df.S4[ , c('SleepQualCro', 'SleepQualAcu', 'SleepQuantCro', 'SleepQuantAcu',
               'Moral_DIL', 'Moral_SCA', 'Moral_CAR')]

df.cor.S5 <- df.S5[ , c('SleepQualCro', 'SleepQualAcu', 'SleepQuantCro', 'SleepQuantAcu',
               'Moral_DIL', 'Moral_SCA')]

df.cor.S6 <- df.S6[ , c('SleepQualCro', 'SleepQualAcu', 'SleepQuantCro', 'SleepQuantAcu',
               'Moral_DIL', 'Moral_SCA')]


s1 <- round(cor(df.cor.S1, use = "pairwise.complete.obs"), 2)
s2 <- round(cor(df.cor.S2, use = "pairwise.complete.obs"), 2)
s3 <- round(cor(df.cor.S3, use = "pairwise.complete.obs"), 2)
s4 <- round(cor(df.cor.S4, use = "pairwise.complete.obs"), 2)
s5 <- round(cor(df.cor.S5, use = "pairwise.complete.obs"), 2)
s6 <- round(cor(df.cor.S6, use = "pairwise.complete.obs"), 2)
```

## Correlation matrix Study 1
```{r}
DT::datatable(s1, options = list(
    scrollX = TRUE,
    dom = c('t'),
    ordering = FALSE))
```

## Correlation matrix Study 2
```{r}
DT::datatable(s2, options = list(
    scrollX = TRUE,
    dom = c('t'),
    ordering = FALSE))
```

## Correlation matrix Study 3
```{r}
DT::datatable(s3, options = list(
    scrollX = TRUE,
    dom = c('t'),
    ordering = FALSE))
```

## Correlation matrix Study 4
```{r}
DT::datatable(s4, options = list(
    scrollX = TRUE,
    dom = c('t'),
    ordering = FALSE))
```

## Correlation matrix Study 5
```{r}
DT::datatable(s5, options = list(
    scrollX = TRUE,
    dom = c('t'),
    ordering = FALSE))
```

## Correlation matrix Study 6
```{r}
DT::datatable(s6, options = list(
    scrollX = TRUE,
    dom = c('t'),
    ordering = FALSE))
```